# Generated by Django 5.1.4 on 2024-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="rights",
            field=models.CharField(default="User", max_length=40),
        ),
    ]
