# Generated by Django 5.1.4 on 2024-12-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_registration_rights"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("pname", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
