# Generated by Django 5.1.4 on 2024-12-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="farmer",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
