# Generated by Django 5.1.4 on 2024-12-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_address_orders_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="order_id",
            field=models.IntegerField(null=True),
        ),
    ]
