# Generated by Django 5.1.4 on 2024-12-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_address_zip_orders_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="cdate",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
