# Generated by Django 5.1.4 on 2024-12-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_payment_cdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
