# Generated by Django 5.1.4 on 2024-12-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0010_orders_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
