from django.urls import path
from myapp import views

urlpatterns=[
    path('',views.index),
    path('signin/',views.signIn),
    path('signup/',views.signUp),
    path('farmer_reg/',views.farmer_reg),
    path('user/',views.user),
    path('adminp/',views.admin),
    path('farmer/',views.farmer),
    path('new_farmers/',views.new_farmers),
    path('app_frm/<id>/',views.app_frm),
    path('rej_frm/<id>/',views.rej_frm),
    path('add_product/',views.add_product),
    path('view_products/',views.view_products),
    path('del_prod/<id>/',views.del_prod),
    path('edit_prod/<id>/',views.edit_product),
    path('products/',views.products),
    path('product_detail/<id>/',views.product_detail),
    path('add_cart/<id>/',views.add_cart),
    path('remove_cart/<id>/',views.remove_cart),
    path('cart/',views.cart),
    path('checkout/',views.checkout),
    path('order_placed/',views.order_placed),
    path('orders/',views.orders),
    path('new_orders/',views.new_orders),
    path('view_orders_products/<oid>/',views.view_orders_products),
    path('ship_product/<oid>/',views.ship_product),
    path('cancel_requests/',views.cancel_requests),
    path('cancel_order/<id>/',views.cancel_order),
    path('accept_cancel/<id>/',views.accept_cancel),
    path('profile/',views.profile),
    path('farmers/',views.farmers),
    path('users/',views.users),
]